name: CoreStaff
version: beta_1.0
author: EdmineCoreTeam
main: fr.edminecoreteam.corestaff.Core
commands:
  vanish:
    description: Commande de vanish
    aliases: [v]
  freeze:
    description: Commande de freeze
  chat:
    description: Commande de gestion du chat
    aliases: [c]